### ISSUE TITLE
Non-integer exponents fail to graph

### ISSUE THREAD

**Issue by CFDougherty** [hieuthi/joplin-plugin-function-plot#2]
Noticed that when plotting exponents that are a decimal or fraction, the graph fails to generate a line. Mousing over the graph presents the correct [x,y] coordinate values over an invisible line.

```function-plot
{
  "width" : 400,
  "height": 300,
  "target": "#closed",
  "xAxis": {"domain": [-1, 4]},
  "yAxis": {"domain": [-5, 25]},
  "data": [{
    "fn": "4x^(1.5)",
    "range": [1, 3],
    "closed": true
  }]
}
```

**Comment by hieuthi** [comment]
It is a known issue with the base library that has no fix that I know off (https://github.com/mauriciopoppe/function-plot/issues/210)

You can use this to draw the plot but you have to remove `"closed": true` since it causes some strange bug
```
{
  "width" : 400,
  "height": 300,
  "target": "#closed",
  "xAxis": {"domain": [-1, 4]},
  "yAxis": {"domain": [-5, 25]},
  "data": [{
    "fn": "4x^(3/2)",
    "range": [1, 3],
    "graphType":"polyline"
  }]
}
```

**Comment by CFDougherty** [comment]
How strange

Thank you!

**Comment by hieuthi** [comment]
Just in case you need it. Even though power with fractional number will cause a problem (due to NaN result with negative number and numeric limitation) for many specific case you can go around it with simple mathematical transformation. For example for your case you can do something like this. So just change your equation to something cause less trouble.

```function-plot
{
  "width" : 400,
  "height": 300,
  "target": "#closed",
  "xAxis": {"domain": [-1, 4]},
  "yAxis": {"domain": [-5, 25]},
  "data": [{
    "fn": "4*sqrt(x^3)",
    "range": [1, 3],
    "closed": true
  }]
}
```
